# Generated by Django 2.1.7 on 2019-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('film_addr', models.CharField(max_length=1000)),
                ('cover_pic', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ori_name', models.CharField(max_length=100)),
                ('prod_year', models.CharField(max_length=100)),
                ('prod_country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('file_format', models.CharField(max_length=100)),
                ('video_size', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('film_length', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=500)),
                ('profile', models.CharField(max_length=2000)),
                ('capt_pic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='phones',
            fields=[
                ('mNo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mMark', models.CharField(max_length=256)),
                ('mPrice', models.CharField(max_length=32)),
                ('mNote', models.CharField(max_length=1024)),
                ('mFile', models.CharField(max_length=256)),
            ],
        ),
    ]
